### ISSUE TITLE
Doesn't work with Wasm,  pointycastle is the problem

### ISSUE THREAD

**Issue by sgehrman** [zathras/misc#5]
│   ├── jovial_svg 1.1.23
│   │   ├── jovial_misc 0.8.5
│   │   │   ├── pointycastle 3.9.1
│   │   │   │   ├── js 0.7.1
│   │   │   │   ├── collection...
│   │   │   │   └── convert...

**Comment by zathras** [comment]
Could you expand on this, please?  I'm not using the WASM runtime, which AFAIK isn't quite ready for primetime yet.

Is this a problem that's likely to be resolved soon in pointycastle?  Or maybe it already is, by a newer version of pointycastle?  Or is it likely to be resolved soon by improvements in Dart's WASM implementation?  Also, why is this a problem -- is there something else that otherwise works with WASM that fails here for only this reason?

**Comment by zathras** [comment]
A link to https://github.com/bcgit/pc-dart/issues/248 is helpful!

**Comment by zathras** [comment]
Split off the part that depends on PointyCastle as of version 0.9.0.
https://github.com/zathras/misc/commit/ba959a751ba7819f3e7da7677b5d9195e5b41881
https://github.com/zathras/misc/commit/34381537b4429fe7fdbd5bdefbc7c4db5b8329f2
